package com.warehouse.warehouse_platform.security.permissions;

public final class TenantPermissions {

    public static final String USERS_VIEW = "tenant.users.view";
    public static final String USERS_CREATE = "tenant.users.create";
    public static final String USERS_EDIT = "tenant.users.edit";
    public static final String USERS_RESET_PASSWORD = "tenant.users.reset_password";
    public static final String USERS_DEACTIVATE = "tenant.users.deactivate";
    public static final String USERS_REACTIVATE = "tenant.users.reactivate";
    public static final String ROLES_EDIT = "tenant.roles.edit";
    public static final String UOMS_VIEW = "tenant.uoms.view";
    public static final String UOMS_CREATE = "tenant.uoms.create";
    public static final String UOMS_EDIT = "tenant.uoms.edit";
    public static final String UOMS_SOFT_DELETE = "tenant.uoms.soft_delete";
    public static final String UOMS_RESTORE = "tenant.uoms.restore";
    public static final String UOMS_HARD_DELETE = "tenant.uoms.hard_delete";
    public static final String SUPPLIERS_VIEW = "tenant.suppliers.view";
    public static final String SUPPLIERS_CREATE = "tenant.suppliers.create";
    public static final String SUPPLIERS_EDIT = "tenant.suppliers.edit";
    public static final String SUPPLIERS_SOFT_DELETE = "tenant.suppliers.soft_delete";
    public static final String SUPPLIERS_RESTORE = "tenant.suppliers.restore";
    public static final String SUPPLIERS_HARD_DELETE = "tenant.suppliers.hard_delete";
    public static final String PRODUCTS_VIEW = "tenant.products.view";
    public static final String PRODUCTS_CREATE = "tenant.products.create";
    public static final String PRODUCTS_EDIT = "tenant.products.edit";
    public static final String PRODUCTS_SOFT_DELETE = "tenant.products.soft_delete";
    public static final String PRODUCTS_RESTORE = "tenant.products.restore";
    public static final String PRODUCTS_HARD_DELETE = "tenant.products.hard_delete";
    public static final String CATEGORIES_VIEW = "tenant.categories.view";
    public static final String CATEGORIES_CREATE = "tenant.categories.create";
    public static final String CATEGORIES_EDIT = "tenant.categories.edit";
    public static final String CATEGORIES_SOFT_DELETE = "tenant.categories.soft_delete";
    public static final String CATEGORIES_RESTORE = "tenant.categories.restore";
    public static final String CATEGORIES_HARD_DELETE = "tenant.categories.hard_delete";
    public static final String WAREHOUSE_VIEW = "tenant.warehouse.view";
    public static final String WAREHOUSE_LAYOUT_MANAGE = "tenant.warehouse.layout.manage";
    public static final String WAREHOUSE_LAYOUT_ACTIVATE = "tenant.warehouse.layout.activate";
    public static final String WAREHOUSE_TEMPLATE_MANAGE = "tenant.warehouse.template.manage";
    public static final String WAREHOUSE_BLOCK_EDIT = "tenant.warehouse.block.edit";
    public static final String WAREHOUSE_HARD_DELETE = "tenant.warehouse.hard_delete";
    public static final String AUDIT_VIEW = "tenant.audit.view";
    public static final String INVENTORY_VIEW = "tenant.inventory.view";
    public static final String INVENTORY_RECEIVE = "tenant.inventory.receive";
    public static final String INVENTORY_TRANSFER = "tenant.inventory.transfer";
    public static final String INVENTORY_ADJUST = "tenant.inventory.adjust";
    public static final String RECEIPTS_VIEW = "tenant.receipts.view";
    public static final String RECEIPTS_CREATE = "tenant.receipts.create";
    public static final String RECEIPTS_EDIT = "tenant.receipts.edit";
    public static final String RECEIPTS_POST = "tenant.receipts.post";
    public static final String RECEIPTS_VOID = "tenant.receipts.void";
    public static final String DISPATCHES_VIEW = "tenant.dispatches.view";
    public static final String DISPATCHES_CREATE = "tenant.dispatches.create";
    public static final String DISPATCHES_EDIT = "tenant.dispatches.edit";
    public static final String DISPATCHES_POST = "tenant.dispatches.post";
    public static final String DISPATCHES_VOID = "tenant.dispatches.void";
    public static final String COUNTING_VIEW = "tenant.counting.view";
    public static final String COUNTING_CREATE = "tenant.counting.create";
    public static final String COUNTING_POST = "tenant.counting.post";
    public static final String COUNTING_VOID = "tenant.counting.void";
    public static final String GIS_FLOOR_PLAN_VIEW = "gis.floorplan.view";
    public static final String GIS_FLOOR_PLAN_MANAGE = "gis.floorplan.manage";
    public static final String GIS_LAYOUT_REGENERATE = "gis.layout.regenerate";
    public static final String GIS_LAYOUT_VIEW = "gis.layout.view";
    public static final String GIS_ZONES_VIEW = "gis.zones.view";
    public static final String GIS_ZONES_MANAGE = "gis.zones.manage";
    public static final String HAZARD_TYPES_VIEW = "tenant.hazard_types.view";
    public static final String HAZARD_TYPES_CREATE = "tenant.hazard_types.create";
    public static final String HAZARD_TYPES_EDIT = "tenant.hazard_types.edit";
    public static final String HAZARD_TYPES_DEACTIVATE = "tenant.hazard_types.deactivate";
    public static final String HAZARD_TYPES_REACTIVATE = "tenant.hazard_types.reactivate";
    public static final String HAZARD_TYPES_HARD_DELETE = "tenant.hazard_types.hard_delete";
    public static final String ZONE_TYPES_VIEW = "tenant.zone_types.view";
    public static final String ZONE_TYPES_CREATE = "tenant.zone_types.create";
    public static final String ZONE_TYPES_EDIT = "tenant.zone_types.edit";
    public static final String ZONE_TYPES_DEACTIVATE = "tenant.zone_types.deactivate";
    public static final String ZONE_TYPES_REACTIVATE = "tenant.zone_types.reactivate";
    public static final String ZONE_TYPES_HARD_DELETE = "tenant.zone_types.hard_delete";
    public static final String GIS_HAZARD_BUFFERS_VIEW = "gis.hazard_buffers.view";
    public static final String GIS_HAZARD_BUFFERS_MANAGE = "gis.hazard_buffers.manage";
    public static final String GIS_HEATMAPS_VIEW = "gis.heatmaps.view";
    public static final String GIS_HEATMAPS_MANAGE = "gis.heatmaps.manage";

    private TenantPermissions() {
    }
}
