export const LANDLORD_PERMISSIONS = {
  TENANTS_VIEW: "landlord.tenants.view",
  TENANTS_CREATE: "landlord.tenants.create",
  USERS_VIEW: "landlord.users.view",
  USERS_CREATE: "landlord.users.create",
  USERS_EDIT: "landlord.users.edit",
  USERS_RESET_PASSWORD: "landlord.users.reset_password",
  USERS_DEACTIVATE: "landlord.users.deactivate",
  USERS_REACTIVATE: "landlord.users.reactivate",
  ROLES_EDIT: "landlord.roles.edit",
} as const;

export const TENANT_PERMISSIONS = {
  USERS_VIEW: "tenant.users.view",
  USERS_CREATE: "tenant.users.create",
  USERS_EDIT: "tenant.users.edit",
  USERS_RESET_PASSWORD: "tenant.users.reset_password",
  USERS_DEACTIVATE: "tenant.users.deactivate",
  USERS_REACTIVATE: "tenant.users.reactivate",
  ROLES_EDIT: "tenant.roles.edit",
  UOMS_VIEW: "tenant.uoms.view",
  UOMS_CREATE: "tenant.uoms.create",
  UOMS_EDIT: "tenant.uoms.edit",
  UOMS_SOFT_DELETE: "tenant.uoms.soft_delete",
  UOMS_RESTORE: "tenant.uoms.restore",
  UOMS_HARD_DELETE: "tenant.uoms.hard_delete",
  SUPPLIERS_VIEW: "tenant.suppliers.view",
  SUPPLIERS_CREATE: "tenant.suppliers.create",
  SUPPLIERS_EDIT: "tenant.suppliers.edit",
  SUPPLIERS_SOFT_DELETE: "tenant.suppliers.soft_delete",
  SUPPLIERS_RESTORE: "tenant.suppliers.restore",
  SUPPLIERS_HARD_DELETE: "tenant.suppliers.hard_delete",
  PRODUCTS_VIEW: "tenant.products.view",
  PRODUCTS_CREATE: "tenant.products.create",
  PRODUCTS_EDIT: "tenant.products.edit",
  PRODUCTS_SOFT_DELETE: "tenant.products.soft_delete",
  PRODUCTS_RESTORE: "tenant.products.restore",
  PRODUCTS_HARD_DELETE: "tenant.products.hard_delete",
  CATEGORIES_VIEW: "tenant.categories.view",
  CATEGORIES_CREATE: "tenant.categories.create",
  CATEGORIES_EDIT: "tenant.categories.edit",
  CATEGORIES_SOFT_DELETE: "tenant.categories.soft_delete",
  CATEGORIES_RESTORE: "tenant.categories.restore",
  CATEGORIES_HARD_DELETE: "tenant.categories.hard_delete",
  WAREHOUSE_VIEW: "tenant.warehouse.view",
  WAREHOUSE_LAYOUT_MANAGE: "tenant.warehouse.layout.manage",
  WAREHOUSE_LAYOUT_ACTIVATE: "tenant.warehouse.layout.activate",
  WAREHOUSE_TEMPLATE_MANAGE: "tenant.warehouse.template.manage",
  WAREHOUSE_BLOCK_EDIT: "tenant.warehouse.block.edit",
  WAREHOUSE_HARD_DELETE: "tenant.warehouse.hard_delete",
  AUDIT_VIEW: "tenant.audit.view",
  INVENTORY_VIEW: "tenant.inventory.view",
  INVENTORY_RECEIVE: "tenant.inventory.receive",
  INVENTORY_TRANSFER: "tenant.inventory.transfer",
  INVENTORY_ADJUST: "tenant.inventory.adjust",
  RECEIPTS_VIEW: "tenant.receipts.view",
  RECEIPTS_CREATE: "tenant.receipts.create",
  RECEIPTS_EDIT: "tenant.receipts.edit",
  RECEIPTS_POST: "tenant.receipts.post",
  RECEIPTS_VOID: "tenant.receipts.void",
  DISPATCHES_VIEW: "tenant.dispatches.view",
  DISPATCHES_CREATE: "tenant.dispatches.create",
  DISPATCHES_EDIT: "tenant.dispatches.edit",
  DISPATCHES_POST: "tenant.dispatches.post",
  DISPATCHES_VOID: "tenant.dispatches.void",
  COUNTING_VIEW: "tenant.counting.view",
  COUNTING_CREATE: "tenant.counting.create",
  COUNTING_POST: "tenant.counting.post",
  COUNTING_VOID: "tenant.counting.void",
  GIS_FLOOR_PLAN_VIEW: "gis.floorplan.view",
  GIS_FLOOR_PLAN_MANAGE: "gis.floorplan.manage",
  GIS_ZONES_VIEW: "gis.zones.view",
  GIS_ZONES_MANAGE: "gis.zones.manage",
} as const;

export type LandlordPermission = (typeof LANDLORD_PERMISSIONS)[keyof typeof LANDLORD_PERMISSIONS];
export type TenantPermission = (typeof TENANT_PERMISSIONS)[keyof typeof TENANT_PERMISSIONS];
