spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: warehouse
    password: warehouse

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: false

  liquibase:
    enabled: false

multitenancy:
  bootstrap-schema: public
  schema-cache:
    maximumSize: 100
    expireAfterAccess: 10
  master:
    schema: master
    repository:
      packages: com.warehouse.warehouse_platform.multi_tenancy.repository
    entityManager:
      packages: com.warehouse.warehouse_platform.multi_tenancy.domain.entity
    liquibase:
      enabled: true
      change-log: classpath:db/changelog/db.changelog-master.yaml
  tenant:
    repository:
      packages: com.warehouse.warehouse_platform.user,com.warehouse.warehouse_platform.auth.session
    entityManager:
      packages: com.warehouse.warehouse_platform.user,com.warehouse.warehouse_platform.auth.session
    liquibase:
      enabled: true
      change-log: classpath:db/changelog/db.changelog-tenant.yaml

security:
  jwt:
    issuer: warehouse-platform-api
    audience: warehouse-platform-web
    access-token-ttl: 10m
    refresh-token-ttl: 14d
    key-id: warehouse-k1
    private-key: file:keys/jwt-private.pem
    public-key: file:keys/jwt-public.pem
  auth:
    refresh-cookie:
      name: refresh_token
      path: /auth
      same-site: Lax
      secure: false
