security:
  jwt:
    private-key: file:src/test/resources/keys/jwt-private.pem
    public-key: file:src/test/resources/keys/jwt-public.pem

geoserver:
  url: ${GEOSERVER_URL:http://localhost:8600/geoserver}
